// Generated by scripts/generate-compat-facade.mjs.
// This compatibility package contains re-export facades only.

export * from '@lk-design-system/lds-core';
export * from '@lk-design-system/lds-theme';
export * from '@lk-design-system/lds-product';
export * from '@lk-design-system/lds-robotics-ui';
