import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const componentsDir = path.join(root, 'components');
const srcDir = path.join(root, 'src');

const groupOrder = [
  'brand',
  'buttons',
  'cards',
  'content',
  'data',
  'editor',
  'feedback',
  'forms',
  'icon',
  'layout',
  'navigation',
  'overlay',
  'robotics',
  'selection',
  'status',
  'viz',
];

const exportPattern = /^export\s+(?:function|const|let|var|class)\s+([A-Za-z_$][\w$]*)/gm;

async function listComponentFiles() {
  const groups = await readdir(componentsDir, { withFileTypes: true });
  const groupNames = groups
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((a, b) => {
      const ai = groupOrder.indexOf(a);
      const bi = groupOrder.indexOf(b);
      if (ai !== -1 || bi !== -1) return (ai === -1 ? 999 : ai) - (bi === -1 ? 999 : bi);
      return a.localeCompare(b);
    });

  const files = [];
  for (const group of groupNames) {
    const groupDir = path.join(componentsDir, group);
    const entries = await readdir(groupDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isFile() && entry.name.endsWith('.jsx')) {
        files.push({
          group,
          fileName: entry.name,
          fullPath: path.join(groupDir, entry.name),
          baseName: entry.name.slice(0, -'.jsx'.length),
        });
      }
    }
  }
  return files;
}

async function getNamedExports(file) {
  const source = await readFile(file.fullPath, 'utf8');
  const names = new Set();
  for (const match of source.matchAll(exportPattern)) {
    names.add(match[1]);
  }
  return [...names].sort((a, b) => a.localeCompare(b));
}

function toPosix(value) {
  return value.split(path.sep).join('/');
}

const files = await listComponentFiles();
const exportsByFile = [];

for (const file of files) {
  const names = await getNamedExports(file);
  if (names.length === 0) continue;
  exportsByFile.push({ ...file, names });
}

const header = [
  '// Auto-generated by scripts/generate-entry.mjs.',
  '// Do not edit this file directly.',
  '',
];

const jsLines = [...header];
const dtsLines = [...header];

for (const file of exportsByFile) {
  const names = file.names.join(', ');
  const jsPath = toPosix(`../components/${file.group}/${file.fileName}`);
  const dtsPath = toPosix(`../components/${file.group}/${file.baseName}`);
  jsLines.push(`export { ${names} } from '${jsPath}';`);
  dtsLines.push(`export { ${names} } from '${dtsPath}';`);
}

await mkdir(srcDir, { recursive: true });
await writeFile(path.join(srcDir, 'index.js'), `${jsLines.join('\n')}\n`, 'utf8');
await writeFile(path.join(srcDir, 'index.d.ts'), `${dtsLines.join('\n')}\n`, 'utf8');

console.log(`Generated ${exportsByFile.length} component export entries.`);
