// GENERATED by scripts/generate-lk-color-system.mjs — do not hand-edit.
// Token-name manifest for the color-system Storybook showcase.
export const ATOMIC = {
  "cool-neutral": {
    "label": "Cool Neutral",
    "steps": [
      5,
      7,
      10,
      15,
      17,
      20,
      22,
      23,
      25,
      30,
      40,
      50,
      60,
      70,
      80,
      90,
      95,
      96,
      97,
      98,
      99
    ]
  },
  "red": {
    "label": "Red",
    "steps": [
      10,
      20,
      30,
      40,
      50,
      60,
      70,
      80,
      90,
      95,
      99
    ]
  },
  "green": {
    "label": "Green",
    "steps": [
      10,
      20,
      30,
      40,
      50,
      60,
      70,
      80,
      90,
      95,
      99
    ]
  },
  "violet": {
    "label": "Violet",
    "steps": [
      0,
      10,
      20,
      30,
      40,
      45,
      50,
      60,
      70,
      80,
      90,
      95,
      99,
      100
    ]
  },
  "neutral": {
    "label": "Neutral",
    "steps": [
      5,
      10,
      15,
      20,
      22,
      30,
      40,
      50,
      60,
      70,
      80,
      90,
      95,
      99
    ]
  },
  "blue": {
    "label": "Blue",
    "steps": [
      10,
      20,
      30,
      40,
      45,
      50,
      55,
      60,
      65,
      70,
      80,
      90,
      95,
      99
    ]
  },
  "orange": {
    "label": "Orange",
    "steps": [
      10,
      20,
      30,
      39,
      40,
      50,
      60,
      70,
      80,
      90,
      95,
      99
    ]
  },
  "red-orange": {
    "label": "Red Orange",
    "steps": [
      10,
      20,
      30,
      40,
      48,
      50,
      60,
      70,
      80,
      90,
      95,
      99
    ]
  },
  "lime": {
    "label": "Lime",
    "steps": [
      0,
      10,
      20,
      30,
      37,
      40,
      50,
      60,
      70,
      80,
      90,
      95,
      99,
      100
    ]
  },
  "cyan": {
    "label": "Cyan",
    "steps": [
      0,
      10,
      20,
      30,
      40,
      50,
      60,
      70,
      80,
      90,
      95,
      99,
      100
    ]
  },
  "light-blue": {
    "label": "Light Blue",
    "steps": [
      0,
      10,
      20,
      30,
      40,
      50,
      60,
      70,
      80,
      90,
      95,
      99,
      100
    ]
  },
  "pink": {
    "label": "Pink",
    "steps": [
      0,
      10,
      20,
      30,
      40,
      46,
      50,
      60,
      70,
      80,
      90,
      95,
      99,
      100
    ]
  },
  "purple": {
    "label": "Purple",
    "steps": [
      0,
      10,
      20,
      30,
      40,
      50,
      60,
      70,
      80,
      90,
      95,
      99,
      100
    ]
  }
};
export const SEMANTIC = ["static-white","primary-normal","background-normal-normal","fill-strong","label-normal","fill-normal","static-black","label-strong","line-normal-normal","line-normal-alternative","inverse-background","inverse-label","primary-strong","primary-heavy","label-neutral","label-alternative","label-assistive","label-disable","background-normal-alternative","background-elevated-normal","background-elevated-alternative","interaction-inactive","interaction-disable","line-normal-neutral","line-normal-_strong","fill-alternative","status-positive","status-cautionary","status-negative","accent-background-lime","accent-background-cyan","accent-background-light-blue","accent-background-violet","accent-background-pink","material-dimmer","inverse-primary","line-solid-normal","line-solid-neutral","line-solid-alternative","line-solid-_strong","accent-background-red-orange","accent-background-purple","accent-foreground-lime","accent-foreground-cyan","accent-foreground-light-blue","accent-foreground-violet","accent-foreground-purple","accent-foreground-pink","accent-foreground-red-orange","accent-foreground-red","accent-foreground-orange","accent-foreground-green","accent-foreground-blue","material-background-onbackground","material-outline-outline","background-transparent-normal","background-transparent-alternative","accent-violet","accent-cyan"];
